### ISSUE TITLE
Requirements for Candidate

### ISSUE THREAD

**Issue by bubunyo** [devcongress/elections-api#20]
like @yawboakye mentioned candidates compete on a ticket of a political part and or as independent. and a candidate is either a presidential candidate or a parliamentary candidate. Any ideas on what the requirement for the candidate model should be?

**Comment by yawboakye** [comment]
Here's what I'm thinking:

A regular human-like model for the candidate (probably call it something else since they only become a candidate when they contest in an election and contest as independent or on a party's ticket). Then we can establish a connection between the person and a party (or not) and an election. Probably using an association model

```ruby
class Candidate < ApplicationRecord
  belongs_to :political_party, required: false
  belongs_to :election
  ...
end
```
That's just a thought.

**Comment by bubunyo** [comment]
also `is_presidential_candidate` to determine if a candidate is a presidential candidate or not. and a validation check if `is_presidential_candidate` is false then is should belong to a constituency.
